<!doctype html>
<html lang="es">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TourPeople</title>
    <link rel="shortcut icon" type="image/png" href="../assets/images/logo.png" />
    <link rel="stylesheet" href="../assets/css/dashboard.min.css" />
    <!-- sweetalert -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.8/sweetalert2.css"
        integrity="sha512-n1PBkhxQLVIma0hnm731gu/40gByOeBjlm5Z/PgwNxhJnyW1wYG8v7gPJDT6jpk0cMHfL8vUGUVjz3t4gXyZYQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- loader -->
    <link rel="stylesheet" href="../assets/css/loader.css">
    <link rel="stylesheet" href="../css/general_users.css" />
    <?php
    if ($seccion == 4) {
        ?>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/quill/2.0.2/quill.bubble.css">
        <?php
    }
    ?>
</head>HOLA



<body>
    <!-- loader -->
    <div class="conLoader" id="loader">
        <span class="loader"></span>
    </div>
    <!--  Body Wrapper -->
    <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
        data-sidebar-position="fixed" data-header-position="fixed">
        <!-- Sidebar Start -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div>
                <div class="brand-logo d-flex align-items-center justify-content-between">
                    <a href="./index.html" class="text-nowrap logo-img">
                        <img src="../assets/images/logo.png" width="180" alt="logo empresarial" />
                    </a>
                    <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                        <i class="ti ti-x fs-8"></i>
                    </div>
                </div>
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
                    <ul id="sidebarnav">
                        <li class="sidebar-item">
                            <a class="sidebar-link <?php if ($seccion == 7)
                                echo 'active'; ?>"
                                href="../inicio-usuarios/" aria-expanded="false">
                                <span>
                                    <i class="ti ti-layout-dashboard"></i>
                                </span>
                                <span class="hide-menu">Inicio</span>
                            </a>
                        </li>
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">SITIOS</span>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link <?php if ($seccion == 3 || $seccion == 4)
                                echo 'active'; ?>"
                                href="../sitios/" aria-expanded="false">
                                <span>
                                    <i class="ti ti-layout-dashboard"></i>
                                </span>
                                <span class="hide-menu">Ver Sitios</span>
                            </a>
                        </li>
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">Hoteles</span>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link <?php if ($seccion == 5 || $seccion == 6)
                                echo 'active'; ?>"
                                href="../hoteles/" aria-expanded="false">
                                <span>
                                    <i class="ti ti-article"></i>
                                </span>
                                <span class="hide-menu">Ver Hoteles</span>
                            </a>
                        </li>
                        <li class="nav-small-cap">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">restaurantes</span>
                        </li>
                        <li class="sidebar-item">
                            <a class="sidebar-link <?php if ($seccion == 9 || $seccion == 10)
                                echo 'active'; ?>"
                                href="../restaurantes/" aria-expanded="false">
                                <span>
                                    <i class="ti ti-article"></i>
                                </span>
                                <span class="hide-menu">Ver Restaurantes</span>
                            </a>
                        </li>

                    </ul>
                    <div class="unlimited-access hide-menu bg-light-primary position-relative mb-7 mt-5 rounded">
                        <div class="d-flex">
                            <div class="unlimited-access-title me-3">
                                <h6 class="fw-semibold fs-4 mb-6 text-dark w-85">Upgrade to pro</h6>
                                <a href="../buypro/" class="btn btn-primary fs-2 fw-semibold lh-sm">Buy Pro</a>
                            </div>
                            <div class="unlimited-access-img">
                                <img src="../assets/images/rocket.png" alt=" logo de compra" class="img-fluid">
                            </div>
                        </div>
                    </div>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!--  Sidebar End -->
        <!--  Main wrapper -->
        <div class="body-wrapper">
            <!--  Header Start -->
            <header class="app-header">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <ul class="navbar-nav">
                        <li class="nav-item d-block d-xl-none">
                            <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse"
                                href="javascript:void(0)">
                                <i class="ti ti-menu-2"></i>
                            </a>
                        </li>
                    </ul>
                    <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                        <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                            <li class="nav-item dropdown">
                                <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    <img src="../upload/imgUsers/<?php echo $_SESSION['user_tour']['imagen']; ?>" alt=""
                                        width="35" height="35" class="rounded-circle">
                                </a>
                                <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up"
                                    aria-labelledby="drop2">
                                    <div class="message-body">
                                        <a href="../salir/"
                                            class="btn btn-outline-primary mx-3 mt-2 d-block salir">salir</a>
                                        <a href="../perfil-usuario/"
                                            class="btn btn-outline-primary mx-3 mt-2 d-block salir">ver mi perfil</a>

                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!--  Header End -->

            <div class="container-fluid">
                <!-- Main start -->
                <main>
                    <!-- dentro del main se incluye el contenido -->
                    <?php include $contenido; ?>
                </main>
                <!-- Main End -->

                <!-- Footer Start -->
                <footer>
                    <div class="py-6 px-6 text-center">
                        <p class="mb-0 fs-4">Design and Developed by <a href="https://adminmart.com/" target="_blank"
                                class="pe-1 text-primary text-decoration-underline">AdminMart.com</a></p>
                    </div>
                </footer>
                <!--Footer End -->
            </div>
        </div>
    </div>
    <!-- jquery librari f-->
    <script src="../assets/js/jquery-3.3.1.min.js"></script>
    <!-- cdn js de sweet alert -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.14.4/sweetalert2.min.js"
        integrity="sha512-a/ljmGyCvVDl+QZXCxw/6hKcG4V7Syo7qmb9lUFTwrP12lCCItvQKeTMBMjtpa+3RE6UZ7gk+/IZzj4H04y4ng=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!-- scrips del main.js -->
    <script src="../js/main.js"></script>
    <script src="../assets/js/bootstrap.bundle.min.js"></script>
    <script src="../assets/js/sidebarmenu.js"></script>
    <script src="../assets/js/app.min.js"></script>
    <script src="../assets/js/simplebar.min.js"></script>
    <script src="../js/main.js"></script>
    <?php
    if ($seccion == 3) {
        ?>
        <script src="../js/sitios.js"></script>
        <?php
    }
    ?>
    <?php
    if ($seccion == 4) {
        ?>
        <script src="https://cdn.jsdelivr.net/npm/quill@2.0.2/dist/quill.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/quill-delta-to-html"></script>
        <script src="../js/detalleSitio.js"></script>
        <?php
    }
    ?>
    <?php
    if ($seccion == 5) {
        ?>
        <script src="../js/hoteles.js"></script>
        <?php
    }
    ?>
    <?php
    if ($seccion == 6) {
        ?>
        <script src="https://cdn.jsdelivr.net/npm/quill@2.0.2/dist/quill.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/quill-delta-to-html"></script>
        <script src="../js/detalleHotel.js"></script>
        <?php
    }
    ?>
     <?php
    if ($seccion == 7) {
    ?>
        <script src="../js/inicioUsuarios.js"></script>
    <?php
    }
    ?>
    <?php
    if ($seccion == 9) {
        ?>
        <script src="../js/restaurantes.js"></script>
        <?php
    }
    ?>
    <?php
    if ($seccion == 10) {
        ?>
        <script src="https://cdn.jsdelivr.net/npm/quill@2.0.2/dist/quill.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/quill-delta-to-html"></script>
        <script src="../js/detalleRestaurante.js"></script>
        <?php
    }
    ?>
    <?php
    if ($seccion == 11) {
        ?>
        <script src="../js/perfil_usuario.js"></script>
        <?php
    }
    ?>


</body>

</html>